# Generated by Django 4.2 on 2023-07-12 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Musics', models.CharField(max_length=100)),
                ('Details', models.FileField(upload_to='')),
                ('Date', models.DateField()),
                ('Emotions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=50)),
                ('Pin', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.BigIntegerField()),
                ('Vehicle', models.CharField(max_length=50)),
                ('LID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drowsiness_Detection_App.login')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedbacks', models.CharField(max_length=300)),
                ('Date', models.DateField()),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drowsiness_Detection_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feelings', models.CharField(max_length=100)),
                ('MID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drowsiness_Detection_App.music')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=300)),
                ('Date', models.DateField()),
                ('Reply', models.CharField(max_length=300)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drowsiness_Detection_App.login')),
            ],
        ),
    ]
