# Generated by Django 4.2 on 2023-07-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drowsiness_Detection_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='Details',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='Musics',
            field=models.FileField(upload_to=''),
        ),
    ]
