# Generated by Django 4.2 on 2023-07-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drowsiness_Detection_App', '0002_alter_music_details_alter_music_musics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emotion',
        ),
    ]
