# Generated by Django 4.2 on 2023-07-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Drowsiness_Detection_App', '0003_delete_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drowsiness_Detection_App.user'),
        ),
    ]
