# Generated by Django 4.2 on 2023-07-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drowsiness_Detection_App', '0004_alter_complaints_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
