# Generated by Django 5.1.2 on 2025-02-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drowsiness_Detection_App', '0005_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='login',
            name='Username',
            field=models.CharField(max_length=30),
        ),
    ]
